### ISSUE TITLE
LLVM Assertion "Invalid type for pointer element!" failed

### ISSUE THREAD

**Issue by tomprogrammer** [frewsxcv/afl.rs#14] opened 2015-09-01 09:15 UTC
I tried to use AFL on the project https://github.com/tomprogrammer/uuid/tree/afl (rather small) but encountered the following error:
```
cargo build
   Compiling uuid v0.1.17 (file:///home/thomas/development/uuid)
afl-llvm-pass 1.77b by <lszekeres@google.com>
rustc: /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/llvm/lib/IR/Type.cpp:737: static llvm::PointerType* llvm::PointerType::get(llvm::Type*, unsigned int): Assertion `isValidElementType(EltTy) && "Invalid type for pointer element!"' failed.
Could not compile `uuid`.
```

My version of AFL is 1.89b, I used `llvm-config` compiled from the rust sources. Do you have a idea what could be the cause of this error?

**Comment by frewsxcv** [comment] 2016-01-26 02:34
Duplicate of https://github.com/frewsxcv/afl.rs/issues/11 which is now solved

**Closed by frewsxcv** 2016-01-26 02:34 UTC
